name: deepdream
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip
  - git
  - matplotlib
  - numpy
  - pytorch-cuda
  - cudatoolkit
  - torchvision
  - torchaudio
  - tqdm
  # pip:
    # - beautifulsoup4
